[[widget]]
id = "kusa"
fetcher = "basic_heatmap"
render = "grid_heatmap"
[widget.options]
cells = [
  [0, 1, 2, 3, 4, 5, 4, 3, 2, 1],
  [1, 2, 3, 4, 5, 4, 3, 2, 1, 0],
  [2, 3, 4, 5, 4, 3, 2, 1, 0, 1],
  [3, 4, 5, 4, 3, 2, 1, 0, 1, 2],
  [4, 5, 4, 3, 2, 1, 0, 1, 2, 3],
  [5, 4, 3, 2, 1, 0, 1, 2, 3, 4],
  [4, 3, 2, 1, 0, 1, 2, 3, 4, 5],
]
